package com.tufano.tufanomovil.database.creates;

import static com.tufano.tufanomovil.database.tables.Clientes.CN_DIRECCION_CLIENTE;
import static com.tufano.tufanomovil.database.tables.Clientes.CN_EMAIL_CLIENTE;
import static com.tufano.tufanomovil.database.tables.Clientes.CN_ESTADO_CLIENTE;
import static com.tufano.tufanomovil.database.tables.Clientes.CN_ESTATUS_CLIENTE;
import static com.tufano.tufanomovil.database.tables.Clientes.CN_ID_CLIENTE;
import static com.tufano.tufanomovil.database.tables.Clientes.CN_RAZON_SOCIAL_CLIENTE;
import static com.tufano.tufanomovil.database.tables.Clientes.CN_RIF_CLIENTE;
import static com.tufano.tufanomovil.database.tables.Clientes.CN_TELEFONO_CLIENTE;
import static com.tufano.tufanomovil.database.tables.Clientes.TABLA_CLIENTES;
import static com.tufano.tufanomovil.database.tables.Colores.CN_ID_COLOR;
import static com.tufano.tufanomovil.database.tables.Colores.CN_NOMBRE_COLOR;
import static com.tufano.tufanomovil.database.tables.Colores.TABLA_COLORES;
import static com.tufano.tufanomovil.database.tables.Pedidos.CN_APELLIDO_VENDEDOR_PEDIDO;
import static com.tufano.tufanomovil.database.tables.Pedidos.CN_CEDULA_VENDEDOR_PEDIDO;
import static com.tufano.tufanomovil.database.tables.Pedidos.CN_DIRECCION_CLIENTE_PEDIDO;
import static com.tufano.tufanomovil.database.tables.Pedidos.CN_EMAIL_CLIENTE_PEDIDO;
import static com.tufano.tufanomovil.database.tables.Pedidos.CN_EMAIL_VENDEDOR_PEDIDO;
import static com.tufano.tufanomovil.database.tables.Pedidos.CN_ESTADO_CLIENTE_PEDIDO;
import static com.tufano.tufanomovil.database.tables.Pedidos.CN_ESTADO_VENDEDOR_PEDIDO;
import static com.tufano.tufanomovil.database.tables.Pedidos.CN_ESTATUS_PEDIDO;
import static com.tufano.tufanomovil.database.tables.Pedidos.CN_FECHA_PEDIDO;
import static com.tufano.tufanomovil.database.tables.Pedidos.CN_ID_PEDIDO;
import static com.tufano.tufanomovil.database.tables.Pedidos.CN_MONTO_PEDIDO;
import static com.tufano.tufanomovil.database.tables.Pedidos.CN_NOMBRE_VENDEDOR_PEDIDO;
import static com.tufano.tufanomovil.database.tables.Pedidos.CN_OBSERVACIONES_PEDIDO;
import static com.tufano.tufanomovil.database.tables.Pedidos.CN_RAZON_SOCIAL_CLIENTE_PEDIDO;
import static com.tufano.tufanomovil.database.tables.Pedidos.CN_RIF_CLIENTE_PEDIDO;
import static com.tufano.tufanomovil.database.tables.Pedidos.CN_TELEFONO_CLIENTE_PEDIDO;
import static com.tufano.tufanomovil.database.tables.Pedidos.CN_TELEFONO_VENDEDOR_PEDIDO;
import static com.tufano.tufanomovil.database.tables.Pedidos.TABLA_PEDIDOS;
import static com.tufano.tufanomovil.database.tables.PedidosDetalles.CN_BULTOS_PEDIDOS_DETALLES;
import static com.tufano.tufanomovil.database.tables.PedidosDetalles.CN_ID_PEDIDOS_DETALLES;
import static com.tufano.tufanomovil.database.tables.PedidosDetalles.CN_ID_PEDIDO_DETALLES;
import static com.tufano.tufanomovil.database.tables.PedidosDetalles.CN_NUMERACION_PEDIDOS_DETALLES;
import static com.tufano.tufanomovil.database.tables.PedidosDetalles.CN_PARES_PEDIDOS_DETALLES;
import static com.tufano.tufanomovil.database.tables.PedidosDetalles.CN_PRECIO_UNITARIO_PEDIDOS_DETALLES;
import static com.tufano.tufanomovil.database.tables.PedidosDetalles.CN_PRODUCTO_COLOR_PEDIDO_DETALLES;
import static com.tufano.tufanomovil.database.tables.PedidosDetalles.CN_PRODUCTO_MODELO_PEDIDO_DETALLES;
import static com.tufano.tufanomovil.database.tables.PedidosDetalles.CN_PRODUCTO_TIPO_PEDIDO_DETALLES;
import static com.tufano.tufanomovil.database.tables.PedidosDetalles.CN_SUBTOTAL_PEDIDOS_DETALLES;
import static com.tufano.tufanomovil.database.tables.PedidosDetalles.CN_TALLA_PEDIDOS_DETALLES;
import static com.tufano.tufanomovil.database.tables.PedidosDetalles.TABLA_PEDIDOS_DETALLES;
import static com.tufano.tufanomovil.database.tables.PedidosEditar.CN_APELLIDO_VENDEDOR_PEDIDO_EDITAR;
import static com.tufano.tufanomovil.database.tables.PedidosEditar.CN_CEDULA_VENDEDOR_PEDIDO_EDITAR;
import static com.tufano.tufanomovil.database.tables.PedidosEditar.CN_DIRECCION_CLIENTE_PEDIDO_EDITAR;
import static com.tufano.tufanomovil.database.tables.PedidosEditar.CN_EMAIL_CLIENTE_PEDIDO_EDITAR;
import static com.tufano.tufanomovil.database.tables.PedidosEditar.CN_EMAIL_VENDEDOR_PEDIDO_EDITAR;
import static com.tufano.tufanomovil.database.tables.PedidosEditar.CN_ESTADO_CLIENTE_PEDIDO_EDITAR;
import static com.tufano.tufanomovil.database.tables.PedidosEditar.CN_ESTADO_VENDEDOR_PEDIDO_EDITAR;
import static com.tufano.tufanomovil.database.tables.PedidosEditar.CN_ESTATUS_PEDIDO_EDITAR;
import static com.tufano.tufanomovil.database.tables.PedidosEditar.CN_FECHA_PEDIDO_EDITAR;
import static com.tufano.tufanomovil.database.tables.PedidosEditar.CN_ID_PEDIDO_EDITAR;
import static com.tufano.tufanomovil.database.tables.PedidosEditar.CN_MONTO_PEDIDO_EDITAR;
import static com.tufano.tufanomovil.database.tables.PedidosEditar.CN_NOMBRE_VENDEDOR_PEDIDO_EDITAR;
import static com.tufano.tufanomovil.database.tables.PedidosEditar.CN_OBSERVACIONES_PEDIDO_EDITAR;
import static com.tufano.tufanomovil.database.tables.PedidosEditar.CN_RAZON_SOCIAL_CLIENTE_PEDIDO_EDITAR;
import static com.tufano.tufanomovil.database.tables.PedidosEditar.CN_RIF_CLIENTE_PEDIDO_EDITAR;
import static com.tufano.tufanomovil.database.tables.PedidosEditar.CN_TELEFONO_CLIENTE_PEDIDO_EDITAR;
import static com.tufano.tufanomovil.database.tables.PedidosEditar.CN_TELEFONO_VENDEDOR_PEDIDO_EDITAR;
import static com.tufano.tufanomovil.database.tables.PedidosEditar.TABLA_PEDIDOS_EDITAR;
import static com.tufano.tufanomovil.database.tables.PedidosEditarDetalles.CN_BULTOS_PEDIDOS_DETALLES_EDITAR;
import static com.tufano.tufanomovil.database.tables.PedidosEditarDetalles.CN_ID_PEDIDOS_DETALLES_EDITAR;
import static com.tufano.tufanomovil.database.tables.PedidosEditarDetalles.CN_ID_PEDIDO_DETALLES_EDITAR;
import static com.tufano.tufanomovil.database.tables.PedidosEditarDetalles.CN_NUMERACION_PEDIDOS_DETALLES_EDITAR;
import static com.tufano.tufanomovil.database.tables.PedidosEditarDetalles.CN_PARES_PEDIDOS_DETALLES_EDITAR;
import static com.tufano.tufanomovil.database.tables.PedidosEditarDetalles.CN_PRECIO_UNITARIO_PEDIDOS_DETALLES_EDITAR;
import static com.tufano.tufanomovil.database.tables.PedidosEditarDetalles.CN_PRODUCTO_COLOR_PEDIDO_DETALLES_EDITAR;
import static com.tufano.tufanomovil.database.tables.PedidosEditarDetalles.CN_PRODUCTO_MODELO_PEDIDO_DETALLES_EDITAR;
import static com.tufano.tufanomovil.database.tables.PedidosEditarDetalles.CN_PRODUCTO_TIPO_PEDIDO_DETALLES_EDITAR;
import static com.tufano.tufanomovil.database.tables.PedidosEditarDetalles.CN_SUBTOTAL_PEDIDOS_DETALLES_EDITAR;
import static com.tufano.tufanomovil.database.tables.PedidosEditarDetalles.CN_TALLA_PEDIDOS_DETALLES_EDITAR;
import static com.tufano.tufanomovil.database.tables.PedidosEditarDetalles.TABLA_PEDIDOS_DETALLES_EDITAR;
import static com.tufano.tufanomovil.database.tables.PedidosTemporales.CN_BULTOS_PEDIDOS_TEMPORALES;
import static com.tufano.tufanomovil.database.tables.PedidosTemporales.CN_ID_PEDIDO_TEMPORALES;
import static com.tufano.tufanomovil.database.tables.PedidosTemporales.CN_ID_PRODUCTO_PEDIDO_TEMPORALES;
import static com.tufano.tufanomovil.database.tables.PedidosTemporales.CN_NUMERACION_PEDIDOS_TEMPORALES;
import static com.tufano.tufanomovil.database.tables.PedidosTemporales.CN_PARES_PEDIDOS_TEMPORALES;
import static com.tufano.tufanomovil.database.tables.PedidosTemporales.CN_PRECIO_UNITARIO_PEDIDOS_TEMPORALES;
import static com.tufano.tufanomovil.database.tables.PedidosTemporales.CN_PRODUCTO_COLOR_PEDIDO_TEMPORALES;
import static com.tufano.tufanomovil.database.tables.PedidosTemporales.CN_PRODUCTO_MODELO_PEDIDO_TEMPORALES;
import static com.tufano.tufanomovil.database.tables.PedidosTemporales.CN_PRODUCTO_TIPO_PEDIDO_TEMPORALES;
import static com.tufano.tufanomovil.database.tables.PedidosTemporales.CN_SUBTOTAL_PEDIDOS_TEMPORALES;
import static com.tufano.tufanomovil.database.tables.PedidosTemporales.CN_TALLA_PEDIDOS_TEMPORALES;
import static com.tufano.tufanomovil.database.tables.PedidosTemporales.TABLA_PEDIDOS_TEMPORALES;
import static com.tufano.tufanomovil.database.tables.Productos.CN_COLOR_PRODUCTO;
import static com.tufano.tufanomovil.database.tables.Productos.CN_ESTATUS_PRODUCTO;
import static com.tufano.tufanomovil.database.tables.Productos.CN_ID_PRODUCTO;
import static com.tufano.tufanomovil.database.tables.Productos.CN_MODELO_PRODUCTO;
import static com.tufano.tufanomovil.database.tables.Productos.CN_NUMERACION_PRODUCTO;
import static com.tufano.tufanomovil.database.tables.Productos.CN_PARES_TALLAS_PRODUCTO;
import static com.tufano.tufanomovil.database.tables.Productos.CN_PRECIO_PRODUCTO;
import static com.tufano.tufanomovil.database.tables.Productos.CN_TALLA_PRODUCTO;
import static com.tufano.tufanomovil.database.tables.Productos.CN_TIPO_PRODUCTO;
import static com.tufano.tufanomovil.database.tables.Productos.TABLA_PRODUCTOS;
import static com.tufano.tufanomovil.database.tables.Tallas.CN_ID_TALLA;
import static com.tufano.tufanomovil.database.tables.Tallas.CN_NOMBRE_TALLA;
import static com.tufano.tufanomovil.database.tables.Tallas.CN_NUMERACION_TALLA;
import static com.tufano.tufanomovil.database.tables.Tallas.TABLA_TALLAS;
import static com.tufano.tufanomovil.database.tables.Tipos.CN_ID_TIPO;
import static com.tufano.tufanomovil.database.tables.Tipos.CN_NOMBRE_TIPO;
import static com.tufano.tufanomovil.database.tables.Tipos.TABLA_TIPOS;
import static com.tufano.tufanomovil.database.tables.Usuarios.CN_APELLIDO;
import static com.tufano.tufanomovil.database.tables.Usuarios.CN_CEDULA;
import static com.tufano.tufanomovil.database.tables.Usuarios.CN_EMAIL;
import static com.tufano.tufanomovil.database.tables.Usuarios.CN_ESTADO;
import static com.tufano.tufanomovil.database.tables.Usuarios.CN_ID_USUARIO;
import static com.tufano.tufanomovil.database.tables.Usuarios.CN_KEY;
import static com.tufano.tufanomovil.database.tables.Usuarios.CN_NOMBRE;
import static com.tufano.tufanomovil.database.tables.Usuarios.CN_NOMBRE_USUARIO;
import static com.tufano.tufanomovil.database.tables.Usuarios.CN_PASSWORD;
import static com.tufano.tufanomovil.database.tables.Usuarios.CN_TELEFONO;
import static com.tufano.tufanomovil.database.tables.Usuarios.TABLA_USUARIO;

/**
 * Desarrollado por Gerson el 5/4/2016.
 *
 * Clase encargada de agrupar todas las sentencias con las cuales la base de datos se generara.
 */
public class CreateSentences
{
    public static final String CREAR_TABLA_USUARIO = "CREATE TABLE "+ TABLA_USUARIO +" ("+ CN_ID_USUARIO +" INTEGER PRIMARY KEY AUTOINCREMENT, "+CN_NOMBRE_USUARIO+" TEXT NOT NULL,"+CN_CEDULA+" TEXT NOT NULL,"+ CN_NOMBRE +" TEXT NOT NULL,"+ CN_APELLIDO +" TEXT NOT NULL,"+ CN_TELEFONO +" TEXT NOT NULL, "+CN_ESTADO+" TEXT NOT NULL, "+CN_EMAIL+" TEXT NOT NULL, "+CN_PASSWORD+" TEXT NOT NULL, "+CN_KEY+" TEXT NOT NULL);";
    public static final String CREAR_TABLA_PRODUCTO = "CREATE TABLE "+ TABLA_PRODUCTOS +" ("+ CN_ID_PRODUCTO +" INTEGER PRIMARY KEY AUTOINCREMENT, "+CN_TALLA_PRODUCTO+" TEXT NOT NULL, "+CN_TIPO_PRODUCTO+" TEXT NOT NULL, "+ CN_MODELO_PRODUCTO +" TEXT NOT NULL, "+CN_COLOR_PRODUCTO+" TEXT NOT NULL, "+CN_PRECIO_PRODUCTO+" TEXT NOT NULL, "+CN_NUMERACION_PRODUCTO+" TEXT NOT NULL, "+ CN_PARES_TALLAS_PRODUCTO +" TEXT NOT NULL, "+ CN_ESTATUS_PRODUCTO +" INTEGER NOT NULL);";
    public static final String CREAR_TABLA_TIPOS = "CREATE TABLE "+TABLA_TIPOS+" ("+CN_ID_TIPO+" INTEGER PRIMARY KEY AUTOINCREMENT, "+CN_NOMBRE_TIPO+" TEXT NOT NULL);";
    public static final String CREAR_TABLA_TALLAS = "CREATE TABLE "+ TABLA_TALLAS +" ("+CN_ID_TALLA+" INTEGER PRIMARY KEY AUTOINCREMENT, "+CN_NOMBRE_TALLA+" TEXT NOT NULL, "+CN_NUMERACION_TALLA+" TEXT NOT NULL);";
    public static final String CREAR_TABLA_COLORES = "CREATE TABLE "+TABLA_COLORES+" ("+CN_ID_COLOR+" INTEGER PRIMARY KEY AUTOINCREMENT, "+CN_NOMBRE_COLOR+" TEXT NOT NULL);";
    public static final String CREAR_TABLA_CLIENTES = "CREATE TABLE "+TABLA_CLIENTES+" ("+CN_ID_CLIENTE+" INTEGER PRIMARY KEY AUTOINCREMENT, "+CN_RAZON_SOCIAL_CLIENTE+" TEXT NOT NULL, "+CN_RIF_CLIENTE+" TEXT NOT NULL, "+CN_ESTADO_CLIENTE+" TEXT NOT NULL, "+CN_TELEFONO_CLIENTE+" TEXT NOT NULL, "+CN_EMAIL_CLIENTE+" TEXT NOT NULL, "+CN_DIRECCION_CLIENTE+" TEXT NOT NULL, "+CN_ESTATUS_CLIENTE+" INTEGER NOT NULL);";
    public static final String CREAR_TABLA_PEDIDOS = "CREATE TABLE "+TABLA_PEDIDOS+" ("+CN_ID_PEDIDO+" INTEGER PRIMARY KEY AUTOINCREMENT, "+CN_RAZON_SOCIAL_CLIENTE_PEDIDO+" TEXT NOT NULL ," +CN_RIF_CLIENTE_PEDIDO+" TEXT NOT NULL, "+CN_ESTADO_CLIENTE_PEDIDO+" TEXT NOT NULL, "+ CN_TELEFONO_CLIENTE_PEDIDO +" TEXT NOT NULL, "+ CN_EMAIL_CLIENTE_PEDIDO +" TEXT NOT NULL, "+CN_DIRECCION_CLIENTE_PEDIDO+" TEXT NOT NULL, "+CN_CEDULA_VENDEDOR_PEDIDO +" TEXT NOT NULL, "+CN_NOMBRE_VENDEDOR_PEDIDO +" TEXT NOT NULL, "+CN_APELLIDO_VENDEDOR_PEDIDO +" TEXT NOT NULL, "+CN_EMAIL_VENDEDOR_PEDIDO+" TEXT NOT NULL, "+CN_TELEFONO_VENDEDOR_PEDIDO +" TEXT NOT NULL, "+CN_ESTADO_VENDEDOR_PEDIDO +" TEXT NOT NULL, "+CN_MONTO_PEDIDO+" TEXT NOT NULL, "+CN_FECHA_PEDIDO+" DATETIME NOT NULL, "+CN_ESTATUS_PEDIDO+" TEXT NOT NULL, "+CN_OBSERVACIONES_PEDIDO+" TEXT NOT NULL);";
    public static final String CREAR_TABLA_PEDIDOS_DETALLES = "CREATE TABLE "+TABLA_PEDIDOS_DETALLES+" ("+CN_ID_PEDIDO_DETALLES+" INTEGER PRIMARY KEY AUTOINCREMENT, "+CN_ID_PEDIDOS_DETALLES+" INTEGER NOT NULL, "+CN_PRODUCTO_TIPO_PEDIDO_DETALLES+" TEXT NOT NULL, "+CN_PRODUCTO_MODELO_PEDIDO_DETALLES+" TEXT NOT NULL, "+CN_PRODUCTO_COLOR_PEDIDO_DETALLES+" TEXT NOT NULL, "+CN_TALLA_PEDIDOS_DETALLES+" TEXT NOT NULL, "+CN_NUMERACION_PEDIDOS_DETALLES+" TEXT NOT NULL, "+CN_PARES_PEDIDOS_DETALLES+" INTEGER NOT NULL, "+CN_BULTOS_PEDIDOS_DETALLES+" INTEGER NOT NULL, "+CN_PRECIO_UNITARIO_PEDIDOS_DETALLES+" TEXT NOT NULL, "+CN_SUBTOTAL_PEDIDOS_DETALLES+" TEXT NOT NULL);";
    public static final String CREAR_TABLA_PEDIDOS_TEMPORALES = "CREATE TABLE "+TABLA_PEDIDOS_TEMPORALES+" ("+CN_ID_PEDIDO_TEMPORALES+" INTEGER PRIMARY KEY AUTOINCREMENT, "+CN_ID_PRODUCTO_PEDIDO_TEMPORALES+" INTEGER NOT NULL, "+CN_PRODUCTO_TIPO_PEDIDO_TEMPORALES+" TEXT NOT NULL, "+CN_PRODUCTO_MODELO_PEDIDO_TEMPORALES+" TEXT NOT NULL,  "+CN_PRODUCTO_COLOR_PEDIDO_TEMPORALES +" TEXT NOT NULL,  "+CN_TALLA_PEDIDOS_TEMPORALES+" TEXT NOT NULL, "+CN_NUMERACION_PEDIDOS_TEMPORALES+" TEXT NOT NULL, "+CN_PARES_PEDIDOS_TEMPORALES+" INTEGER NOT NULL, "+CN_BULTOS_PEDIDOS_TEMPORALES+" INTEGER NOT NULL, "+CN_PRECIO_UNITARIO_PEDIDOS_TEMPORALES+" TEXT NOT NULL, "+CN_SUBTOTAL_PEDIDOS_TEMPORALES+" TEXT NOT NULL);";
    public static final String CREAR_TABLA_PEDIDOS_EDITAR = "CREATE TABLE "+TABLA_PEDIDOS_EDITAR+" ("+CN_ID_PEDIDO_EDITAR+" INTEGER PRIMARY KEY AUTOINCREMENT, "+CN_RAZON_SOCIAL_CLIENTE_PEDIDO_EDITAR+" TEXT NOT NULL ," +CN_RIF_CLIENTE_PEDIDO_EDITAR+" TEXT NOT NULL, "+CN_ESTADO_CLIENTE_PEDIDO_EDITAR+" TEXT NOT NULL, "+ CN_TELEFONO_CLIENTE_PEDIDO_EDITAR +" TEXT NOT NULL, "+ CN_EMAIL_CLIENTE_PEDIDO_EDITAR +" TEXT NOT NULL, "+CN_DIRECCION_CLIENTE_PEDIDO_EDITAR+" TEXT NOT NULL, "+CN_CEDULA_VENDEDOR_PEDIDO_EDITAR +" TEXT NOT NULL, "+CN_NOMBRE_VENDEDOR_PEDIDO_EDITAR +" TEXT NOT NULL, "+CN_APELLIDO_VENDEDOR_PEDIDO_EDITAR +" TEXT NOT NULL, "+CN_EMAIL_VENDEDOR_PEDIDO_EDITAR+" TEXT NOT NULL, "+CN_TELEFONO_VENDEDOR_PEDIDO_EDITAR +" TEXT NOT NULL, "+CN_ESTADO_VENDEDOR_PEDIDO_EDITAR +" TEXT NOT NULL, "+CN_MONTO_PEDIDO_EDITAR+" TEXT NOT NULL, "+CN_FECHA_PEDIDO_EDITAR+" DATETIME NOT NULL, "+CN_ESTATUS_PEDIDO_EDITAR+" TEXT NOT NULL, "+CN_OBSERVACIONES_PEDIDO_EDITAR+" TEXT NOT NULL);";
    public static final String CREAR_TABLA_PEDIDOS_DETALLES_EDITAR = "CREATE TABLE "+TABLA_PEDIDOS_DETALLES_EDITAR+" ("+CN_ID_PEDIDO_DETALLES_EDITAR+" INTEGER PRIMARY KEY AUTOINCREMENT, "+CN_ID_PEDIDOS_DETALLES_EDITAR+" INTEGER NOT NULL, "+CN_PRODUCTO_TIPO_PEDIDO_DETALLES_EDITAR+" TEXT NOT NULL, "+CN_PRODUCTO_MODELO_PEDIDO_DETALLES_EDITAR+" TEXT NOT NULL, "+CN_PRODUCTO_COLOR_PEDIDO_DETALLES_EDITAR+" TEXT NOT NULL, "+CN_TALLA_PEDIDOS_DETALLES_EDITAR+" TEXT NOT NULL, "+CN_NUMERACION_PEDIDOS_DETALLES_EDITAR+" TEXT NOT NULL, "+CN_PARES_PEDIDOS_DETALLES_EDITAR+" INTEGER NOT NULL, "+CN_BULTOS_PEDIDOS_DETALLES_EDITAR+" INTEGER NOT NULL, "+CN_PRECIO_UNITARIO_PEDIDOS_DETALLES_EDITAR+" TEXT NOT NULL, "+CN_SUBTOTAL_PEDIDOS_DETALLES_EDITAR+" TEXT NOT NULL);";
}